# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import drone_pb2 as drone__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in drone_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DroneServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetEnvironment = channel.unary_unary(
                '/dronecontrol.DroneService/SetEnvironment',
                request_serializer=drone__pb2.SetEnvironmentRequest.SerializeToString,
                response_deserializer=drone__pb2.SetEnvironmentResponse.FromString,
                _registered_method=True)
        self.GetDirection = channel.unary_unary(
                '/dronecontrol.DroneService/GetDirection',
                request_serializer=drone__pb2.DirectionRequest.SerializeToString,
                response_deserializer=drone__pb2.DirectionResponse.FromString,
                _registered_method=True)


class DroneServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDirection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DroneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEnvironment,
                    request_deserializer=drone__pb2.SetEnvironmentRequest.FromString,
                    response_serializer=drone__pb2.SetEnvironmentResponse.SerializeToString,
            ),
            'GetDirection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDirection,
                    request_deserializer=drone__pb2.DirectionRequest.FromString,
                    response_serializer=drone__pb2.DirectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dronecontrol.DroneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dronecontrol.DroneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DroneService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dronecontrol.DroneService/SetEnvironment',
            drone__pb2.SetEnvironmentRequest.SerializeToString,
            drone__pb2.SetEnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDirection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dronecontrol.DroneService/GetDirection',
            drone__pb2.DirectionRequest.SerializeToString,
            drone__pb2.DirectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
