# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: hyrl_api/drone.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List, Optional

import betterproto
import grpclib


class HeadingDirection(betterproto.Enum):
    RESERVED = 0
    STRAIGHT = 1
    LEFT = 2
    HARD_LEFT = 3
    RIGHT = 4
    HARD_RIGHT = 5


class DirectionRequestModelType(betterproto.Enum):
    STANDARD = 0
    HYBRID = 1


@dataclass
class DroneState(betterproto.Message):
    """define drone state"""

    x: float = betterproto.float_field(1)
    y: float = betterproto.float_field(2)
    z: float = betterproto.float_field(3)


@dataclass
class TrajectoryRequest(betterproto.Message):
    current_state: "DroneState" = betterproto.message_field(1)
    target_state: "DroneState" = betterproto.message_field(2)
    num_waypoints: int = betterproto.uint32_field(3)
    duration_s: int = betterproto.uint32_field(4)


@dataclass
class TrajectoryResponse(betterproto.Message):
    trajectory: List["DroneState"] = betterproto.message_field(1)


@dataclass
class DirectionRequest(betterproto.Message):
    """DEFINE DIRECTION REQUEST"""

    drone_state: "DroneState" = betterproto.message_field(1)
    model_type: "DirectionRequestModelType" = betterproto.enum_field(2)


@dataclass
class DirectionResponse(betterproto.Message):
    """DEFINE DIRECTION RESPONSE"""

    discrete_heading: "DiscreteHeading" = betterproto.message_field(
        2, group="control_type"
    )
    continuous_heading: "ContinuousHeading" = betterproto.message_field(
        3, group="control_type"
    )


@dataclass
class DiscreteHeading(betterproto.Message):
    direction: "HeadingDirection" = betterproto.enum_field(1)


@dataclass
class ContinuousHeading(betterproto.Message):
    rad: float = betterproto.float_field(1)


class ObstacleAvoidanceServiceStub(betterproto.ServiceStub):
    async def get_direction(
        self,
        *,
        drone_state: Optional["DroneState"] = None,
        model_type: "DirectionRequestModelType" = 0,
    ) -> DirectionResponse:
        request = DirectionRequest()
        if drone_state is not None:
            request.drone_state = drone_state
        request.model_type = model_type

        return await self._unary_unary(
            "/hyrl.ObstacleAvoidanceService/GetDirection",
            request,
            DirectionResponse,
        )

    async def get_trajectory(
        self,
        *,
        current_state: Optional["DroneState"] = None,
        target_state: Optional["DroneState"] = None,
        num_waypoints: int = 0,
        duration_s: int = 0,
    ) -> TrajectoryResponse:
        request = TrajectoryRequest()
        if current_state is not None:
            request.current_state = current_state
        if target_state is not None:
            request.target_state = target_state
        request.num_waypoints = num_waypoints
        request.duration_s = duration_s

        return await self._unary_unary(
            "/hyrl.ObstacleAvoidanceService/GetTrajectory",
            request,
            TrajectoryResponse,
        )
