name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Setup development environment
        run: |
          nix develop --command bash -lc '
            uv sync --extra dev
            uv pip install -e .
            make protos
          '

      - name: Install grpcurl
        run: |
          curl -sSL \
            https://github.com/fullstorydev/grpcurl/releases/download/v1.9.1/grpcurl_1.9.1_linux_x86_64.tar.gz \
            | tar -xz -C /usr/local/bin grpcurl

      - name: Start server and run RPC test
        run: |
          nix develop --command bash -lc '
            make run &
            SERVER_PID=$!
            sleep 10
            grpcurl -plaintext \
              -import-path protos/hyrl_api \
              -proto obstacle_avoidance.proto \
              -d "{\"drone_state\":{\"x\":1.5,\"y\":0,\"z\":0}}\" \
              127.0.0.1:50051 hyrl.ObstacleAvoidanceService.GetDirection \
              > response.json
            grep -q "\"direction\":" response.json
            kill $SERVER_PID
          '
