name: Format and Commit

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository with full history for git operations
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for git diff

      # Set up Python 3.13
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Install uv
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      # Install dependencies with uv (including dev for Black)
      - name: Install dependencies
        run: |
          uv sync --extra dev

      # Run Black to reformat code and capture changes
      - name: Reformat with Black
        run: |
          # Run Black to reformat and capture output
          uv run black src/ > black_output.txt 2>&1 || true
          # Check if any files were reformatted by looking for "reformatted" in output
          if grep -q "reformatted" black_output.txt; then
            echo "Files were reformatted by Black:"
            grep "reformatted" black_output.txt | awk '{print $2}'
          else
            echo "No files needed reformatting."
          fi
